swagger: '2.0'
info:
  version: "1.0.1"
  title: 'FINDEMY Web Application'
  description: 'Web Application for Investment tracking and Metrics Visualizations'
host: findemybackedcode.onrender.com
schemes:
  - https
securityDefinitions:
  bearerAuth:   
    type: apiKey
    name: Authorization
    in: header
    description: Enter the Bearer token in the format "Bearer <token>"
paths:
  /auth/login:
    post:
      tags:
      - User Auth
      summary: User Login
      description: |
        User should provide email id and password. On successful authentication user gets userid, access token and refresh token.
        
        **Mandatory Fields:**
            email
            password
      parameters:
        - in: body
          name: user_credentials
          description: User credentials (email and password)
          schema:
            $ref: '#/definitions/LoginCredentials'
      responses:
        '200':
          description: User Logged In Successfully
          schema:
            $ref: '#/definitions/LoginSuccessResponse'
        '500':
          description: Server or Database Failure
          schema:
            $ref: '#/definitions/ErrorMessage'
        '404':
          description: User does not exists / Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        '401':
          description: Username or Password does not match
          schema:
            $ref: '#/definitions/ErrorMessage'
        '400':
          description: Invalid Request / Invalid Payload
          schema:
            $ref: '#/definitions/ErrorMessage'
  /auth/register:
    post:
      tags:
      - User Auth
      summary: User Registration
      description: |
        User should provide emailId, password, confirmPassword and phoneNumber. If all the details are valid and user does not exists, then a new user will be created.
        
        **Mandatory Fields:**
            email
            password
            confirm_password
            phone_number
      parameters:
        - in: body
          name: registration_credentials
          description: User credentials
          schema:
            $ref: '#/definitions/RegistrationCredentials'
      responses:
        '201':
          description: User Registered Successfully
          schema:
            $ref: '#/definitions/RegistrationSuccessResponse'
        '500':
          description: Server or Database Failure
          schema:
            $ref: '#/definitions/ErrorMessage'
        '401':
          description: User already exists
          schema:
            $ref: '#/definitions/ErrorMessage'
        '400':
          description: Invalid Request / Invalid Payload
          schema:
            $ref: '#/definitions/ErrorMessage'
  /stock/getInvestementHistory:
   get:
      tags:
      - Stocks
      summary: Get Investment History
      security:
        - bearerAuth: []
      description: |
        Get the details of all stocks investements made by user till date.
      responses:
        '200':
          description: Data Retrieved Successfully
          schema:
            $ref: '#/definitions/InvestmentHistoryModel'
        '500':
          description: Server or Database Failure
          schema:
            $ref: '#/definitions/ErrorMessage'
definitions:
  InvestmentHistoryModel:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/InvestmentData'
  InvestmentData:
    type: object
    properties:
      id:
        type: integer
      uid: 
        type: integer
      stockSymbol:
        type: string
      stockName:
        type: string
      perSharePrice:
        type: number
      numberOfShares: 
        type: integer
  LoginCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
  RegistrationCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      confirm_password:
        type: string
      phone_number:
        type: string
    required:
      - email
      - password
      - confirm_password
      - phone_number
  LoginSuccessResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
      data:
        type: object
        properties:
          accessToken:
            type: string
          refreshToken:
            type: string  
          id:
            type: integer
  RegistrationSuccessResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
      data:
        type: object
        properties:
          id:
            type: integer
          email:
            type: string  
          password:
            type: string
          phone_number:
            type: string
          created_at:
            type: string
          modified_at:
            type: string
  ErrorMessage:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
